SELECT * FROM STORAGE_RATE WHERE SERVICE_CODE = 3121 AND COMMODITY_CODE = 4361 ORDER BY START_DAY;


select storage_rate.*, cp.COMMODITY_NAME
from storage_rate, commodity_profile cp
where storage_rate.commodity_code in (1172, 3302, 3304, 3399)
and storage_rate.commodity_code=cp.COMMODITY_CODE
order by storage_rate.service_code, storage_rate.commodity_code, start_day
;

select *
from commodity_profile cp
where cp.COMMODITY_CODE in (1172, 3302, 3304, 3399)
;


select count(*)
from cargo_tracking ct
where ct.STORAGE_END between '29-may-2006' and '31-may-2006'
and ct.LOT_NUM in
(
select cm.CONTAINER_NUM
from cargo_manifest cm
where cm.LR_NUM in (9284,9305)
)
; 


select cm.LR_NUM, cm.CONTAINER_NUM, cm.COMMODITY_CODE 
from cargo_manifest cm
where cm.CONTAINER_NUM in 
(
select ct.LOT_NUM
from cargo_tracking ct
where ct.STORAGE_END between '29-may-2006' and '30-may-2006'
)
; 


select ct.LOT_NUM, ct.COMMODITY_CODE, ct.STORAGE_CUST_ID, ct.STORAGE_END
from cargo_tracking ct
where ct.STORAGE_END between '29-may-2006' and '30-may-2006'
and ct.QTY_RECEIVED >0


SELECT * FROM CARGO_TRACKING WHERE QTY_RECEIVED > 0 AND WHSE_RCPT_NUM > 0 AND COMMODITY_CODE NOT IN (1272, 6172, 8101) AND STORAGE_END >= TO_DATE('5/29/2006', 'MM/DD/YYYY') AND STORAGE_END <= TO_DATE('5/30/2006', 'MM/DD/YYYY') ORDER BY STORAGE_END
;


SELECT * FROM STORAGE_RATE_TEST WHERE CUSTOMER_ID=1916 AND LR_NUM = 9116 AND SERVICE_CODE = 3121 AND COMMODITY_CODE = 4260 ORDER BY START_DAY 
;

SELECT * FROM STORAGE_RATE_TEST 
WHERE 
--CUSTOMER_ID=1916 
--AND LR_NUM = 9116 
--AND 
SERVICE_CODE = 3121 
AND COMMODITY_CODE = 4260 
ORDER BY START_DAY
; 


SELECT * FROM STORAGE_RATE WHERE LR_NUM = 9116 AND SERVICE_CODE = 3121 AND COMMODITY_CODE = 4260 ORDER BY START_DAY 


SELECT * FROM
STORAGE_RATE_TEST;



SELECT CT.LOT_NUM, CT.FREE_TIME_END, CT.STORAGE_END
FROM CARGO_TRACKING CT
WHERE CT.LOT_NUM
in
(
SELECT CM.CONTAINER_NUM
FROM CARGO_MANIFEST CM
WHERE CM.LR_NUM in (9288)
)




SELECT MAX(CT.STORAGE_END) 
FROM CARGO_TRACKING CT



SELECT * FROM STORAGE_RATE_TEST
ORDER by SERVICE_CODE, COMMODITY_CODE, START_DAY;

SELECT * 
FROM STORAGE_RATE_TEST SR
WHERE SR.SERVICE_CODE=3111 
AND SR.COMMODITY_CODE=3399
AND SR.START_DAY < 42
AND SR.END_DAY > 42
AND SR.LR_NUM=8605
-- AND SR.CUSTOMER_ID=
;
 
SELECT * FROM STORAGE_RATE_TEST SR WHERE SR.SERVICE_CODE =3121 AND SR.COMMODITY_CODE=4260;

SELECT * FROM STORAGE_RATE_TEST SR WHERE SR.SERVICE_CODE =3121 AND SR.COMMODITY_CODE=4260 AND SR.START_DAY < 8235 AND SR.END_DAY > 8235 AND SR.LR_NUM IS NULL AND SR.CUSTOMER IS NULL;


SELECT * FROM STORAGE_RATE_TEST SR WHERE SR.SERVICE_CODE =3121 AND SR.COMMODITY_CODE=4260 AND SR.START_DAY IS NULL AND SR.END_DAY IS NULL AND SR.LR_NUM IS NULL AND SR.CUSTOMER_ID IS NULL;